// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package expense

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	shared "bandcash/models/shared"
)

func PaidAtDialog() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		submitExpr := `!$paidAtDialog.fetching && (el.open && el.close(), $paidAtDialog.fetching = true, @post($paidAtDialog.url, {mode: $paidAtDialog.mode || 'single', tableQuery: $tableQuery}))`
		templ_7745c5c3_Err = shared.PaidAtDialog(shared.PaidAtDialogProps{
			ID:              "paid-at-popover",
			PopoverClass:    "paid-at-popover",
			DialogClass:     "paid-at-dialog",
			LabelledBy:      "paid-at-title",
			DescribedBy:     "paid-at-message",
			Signal:          "paidAtDialog",
			SubmitExpr:      submitExpr,
			InputID:         "paid-at-input",
			ClearID:         "paid-at-clear",
			CancelID:        "paid-at-cancel",
			SubmitID:        "paid-at-submit",
			PlaceholderExpr: "$paidAtDialog.placeholder || ''",
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
