service: bandcash
image: peterszarvashu/bandcash-staging

servers:
  - bandcash_staging

proxy:
  host: staging.bandcash.app
  app_port: 2222
  ssl: true
  healthcheck:
    path: /health
    interval: 3
    timeout: 5

registry:
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64
  remote: ssh://peti@bandcash_staging
  local: false

ssh:
  user: peti

volumes:
  - bandcash_staging_data:/storage

env:
  secret:
    - APP_ENV
    - HOST
    - PORT
    - URL
    - DB_PATH
    - LOG_LEVEL
    - LOG_FOLDER
    - LOG_PREFIX
    - DISABLE_RATE_LIMIT
    - PADDLE_ENV
    - SUPERADMIN_EMAIL
    - SMTP_HOST
    - SMTP_PORT
    - EMAIL_FROM
    - SMTP_USERNAME
    - SMTP_PASSWORD
    - PADDLE_API_KEY
    - PADDLE_API_BASE_URL
    - PADDLE_CLIENT_TOKEN
    - PADDLE_WEBHOOK_SECRET
    - PADDLE_PRICE_ID

accessories:
  better-stack:
    service: better-stack
    image: timberio/vector:0.42.0-debian
    host: bandcash_staging
    cmd: "--config /etc/vector/vector.toml"
    files:
      - config/observability/vector.staging.toml:/etc/vector/vector.toml:ro
    directories:
      - better-stack-staging-data:/var/lib/vector
    volumes:
      - bandcash_staging_data:/storage:ro
    env:
      secret:
        - BETTER_STACK_URI
        - BETTER_STACK_SOURCE_TOKEN
