ALTER TABLE billing_customers RENAME COLUMN paddle_customer_id TO provider_customer_id;
DROP INDEX IF EXISTS idx_billing_customers_paddle_customer_id;
CREATE INDEX IF NOT EXISTS idx_billing_customers_provider_customer_id ON billing_customers(provider_customer_id);

ALTER TABLE billing_subscriptions RENAME COLUMN paddle_subscription_id TO provider_subscription_id;
ALTER TABLE billing_subscriptions RENAME COLUMN paddle_price_id TO provider_variant_id;
