// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package db

import (
	"context"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (id, group_id, title, time, description, amount)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, group_id, title, time, description, amount, created_at, updated_at
`

type CreateEventParams struct {
	ID          string `json:"id"`
	GroupID     string `json:"group_id"`
	Title       string `json:"title"`
	Time        string `json:"time"`
	Description string `json:"description"`
	Amount      int64  `json:"amount"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, createEvent,
		arg.ID,
		arg.GroupID,
		arg.Title,
		arg.Time,
		arg.Description,
		arg.Amount,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Title,
		&i.Time,
		&i.Description,
		&i.Amount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAllEvents = `-- name: DeleteAllEvents :exec
DELETE FROM events
`

func (q *Queries) DeleteAllEvents(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllEvents)
	return err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events
WHERE id = ? AND group_id = ?
`

type DeleteEventParams struct {
	ID      string `json:"id"`
	GroupID string `json:"group_id"`
}

func (q *Queries) DeleteEvent(ctx context.Context, arg DeleteEventParams) error {
	_, err := q.db.ExecContext(ctx, deleteEvent, arg.ID, arg.GroupID)
	return err
}

const getEvent = `-- name: GetEvent :one
SELECT id, group_id, title, time, description, amount, created_at, updated_at FROM events
WHERE id = ? AND group_id = ?
`

type GetEventParams struct {
	ID      string `json:"id"`
	GroupID string `json:"group_id"`
}

func (q *Queries) GetEvent(ctx context.Context, arg GetEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEvent, arg.ID, arg.GroupID)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Title,
		&i.Time,
		&i.Description,
		&i.Amount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEvents = `-- name: ListEvents :many
SELECT id, group_id, title, time, description, amount, created_at, updated_at FROM events
WHERE group_id = ?
ORDER BY time ASC
`

func (q *Queries) ListEvents(ctx context.Context, groupID string) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEvents, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Title,
			&i.Time,
			&i.Description,
			&i.Amount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events
SET title = ?, time = ?, description = ?, amount = ?
WHERE id = ? AND group_id = ?
RETURNING id, group_id, title, time, description, amount, created_at, updated_at
`

type UpdateEventParams struct {
	Title       string `json:"title"`
	Time        string `json:"time"`
	Description string `json:"description"`
	Amount      int64  `json:"amount"`
	ID          string `json:"id"`
	GroupID     string `json:"group_id"`
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, updateEvent,
		arg.Title,
		arg.Time,
		arg.Description,
		arg.Amount,
		arg.ID,
		arg.GroupID,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Title,
		&i.Time,
		&i.Description,
		&i.Amount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
