// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: participants.sql

package db

import (
	"context"
	"database/sql"
)

const addParticipant = `-- name: AddParticipant :one
INSERT INTO participants (event_id, member_id, amount, expense)
VALUES (?, ?, ?, ?)
RETURNING event_id, member_id, amount, created_at, updated_at, expense
`

type AddParticipantParams struct {
	EventID  int64 `json:"event_id"`
	MemberID int64 `json:"member_id"`
	Amount   int64 `json:"amount"`
	Expense  int64 `json:"expense"`
}

func (q *Queries) AddParticipant(ctx context.Context, arg AddParticipantParams) (Participant, error) {
	row := q.db.QueryRowContext(ctx, addParticipant,
		arg.EventID,
		arg.MemberID,
		arg.Amount,
		arg.Expense,
	)
	var i Participant
	err := row.Scan(
		&i.EventID,
		&i.MemberID,
		&i.Amount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Expense,
	)
	return i, err
}

const listParticipantsByEvent = `-- name: ListParticipantsByEvent :many
SELECT members.id, members.name, members.description, members.created_at, members.updated_at, participants.amount AS participant_amount, participants.expense AS participant_expense
FROM members
JOIN participants ON participants.member_id = members.id
WHERE participants.event_id = ?
ORDER BY members.name ASC
`

type ListParticipantsByEventRow struct {
	ID                 int64        `json:"id"`
	Name               string       `json:"name"`
	Description        string       `json:"description"`
	CreatedAt          sql.NullTime `json:"created_at"`
	UpdatedAt          sql.NullTime `json:"updated_at"`
	ParticipantAmount  int64        `json:"participant_amount"`
	ParticipantExpense int64        `json:"participant_expense"`
}

func (q *Queries) ListParticipantsByEvent(ctx context.Context, eventID int64) ([]ListParticipantsByEventRow, error) {
	rows, err := q.db.QueryContext(ctx, listParticipantsByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListParticipantsByEventRow{}
	for rows.Next() {
		var i ListParticipantsByEventRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParticipantAmount,
			&i.ParticipantExpense,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParticipantsByMember = `-- name: ListParticipantsByMember :many
SELECT events.id, events.title, events.time, events.description, events.amount, events.created_at, events.updated_at, participants.amount AS participant_amount, participants.expense AS participant_expense
FROM events
JOIN participants ON participants.event_id = events.id
WHERE participants.member_id = ?
ORDER BY events.created_at DESC
`

type ListParticipantsByMemberRow struct {
	ID                 int64        `json:"id"`
	Title              string       `json:"title"`
	Time               string       `json:"time"`
	Description        string       `json:"description"`
	Amount             int64        `json:"amount"`
	CreatedAt          sql.NullTime `json:"created_at"`
	UpdatedAt          sql.NullTime `json:"updated_at"`
	ParticipantAmount  int64        `json:"participant_amount"`
	ParticipantExpense int64        `json:"participant_expense"`
}

func (q *Queries) ListParticipantsByMember(ctx context.Context, memberID int64) ([]ListParticipantsByMemberRow, error) {
	rows, err := q.db.QueryContext(ctx, listParticipantsByMember, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListParticipantsByMemberRow{}
	for rows.Next() {
		var i ListParticipantsByMemberRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Time,
			&i.Description,
			&i.Amount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParticipantAmount,
			&i.ParticipantExpense,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeParticipant = `-- name: RemoveParticipant :exec
DELETE FROM participants
WHERE event_id = ? AND member_id = ?
`

type RemoveParticipantParams struct {
	EventID  int64 `json:"event_id"`
	MemberID int64 `json:"member_id"`
}

func (q *Queries) RemoveParticipant(ctx context.Context, arg RemoveParticipantParams) error {
	_, err := q.db.ExecContext(ctx, removeParticipant, arg.EventID, arg.MemberID)
	return err
}

const updateParticipant = `-- name: UpdateParticipant :exec
UPDATE participants
SET amount = ?, expense = ?
WHERE event_id = ? AND member_id = ?
`

type UpdateParticipantParams struct {
	Amount   int64 `json:"amount"`
	Expense  int64 `json:"expense"`
	EventID  int64 `json:"event_id"`
	MemberID int64 `json:"member_id"`
}

func (q *Queries) UpdateParticipant(ctx context.Context, arg UpdateParticipantParams) error {
	_, err := q.db.ExecContext(ctx, updateParticipant,
		arg.Amount,
		arg.Expense,
		arg.EventID,
		arg.MemberID,
	)
	return err
}
